export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export const START_LOADING = 'START_LOADING';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
